#!/usr/bin/env python
"""units.py - Some measurement units"""

BYTES = 1
KIBIBYTES = 1024 * BYTES
MIBIBYTES = 1024 * KIBIBYTES
GIBIBYTES = 1024 * MIBIBYTES

KILOBYTES = 1000 * BYTES
MEGABYTES = 1000 * KILOBYTES
GIGABYTES = 1000 * MEGABYTES
TERABYTES = 1000 * GIGABYTES

KiB = KIBIBYTES
MiB = MIBIBYTES
GiB = GIBIBYTES

KB = KILOBYTES
GB = GIGABYTES
TB = TERABYTES
